=== Symfony-Plugins/sfYahooGeocoderPlugin/data/xsd/GeocodeResponse.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="urn:yahoo:maps"
  xmlns="urn:yahoo:maps"
  elementFormDefault="qualified">

	<xs:element name="ResultSet">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ResultType" minOccurs="0" maxOccurs="50" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ResultType">
		<xs:sequence>
			<xs:element name="Latitude" type="xs:decimal" />
			<xs:element name="Longitude" type="xs:decimal" />
			<xs:element name="Address" type="xs:string" />
			<xs:element name="City" type="xs:string" />
			<xs:element name="State" type="xs:string" />
			<xs:element name="Zip" type="xs:string" />
			<xs:element name="Country" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="precision" type="xs:string" />
		<xs:attribute name="warning" type="xs:string" use="optional"/>
	</xs:complexType>
	
</xs:schema>
<!-- ws03.ydn.re2.yahoo.com compressed/chunked Thu Aug  6 13:42:27 PDT 2009 -->

=== Symfony-Plugins/sfYahooGeocoderPlugin/test/fixtures/sfYahooGeocoderResponseXml.xml
<?xml version="1.0"?>
<ResultSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:yahoo:maps" xsi:schemaLocation="urn:yahoo:maps http://api.local.yahoo.com/MapsService/V1/GeocodeResponse.xsd">
	<Result precision="address">
		<Latitude>48.870480</Latitude>
		<Longitude>2.305420</Longitude>
		<Address>Avenue des Champs-Élysées</Address>
		<City>Paris</City>
		<State>France</State>
		<Zip>75008</Zip>
		<Country>FR</Country>
	</Result>
</ResultSet>

=== Symfony-Plugins/sfYahooGeocoderPlugin/test/fixtures/sfYahooGeocoderResponseCollectionXml.xml
<?xml version="1.0"?>
<ResultSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:yahoo:maps" xsi:schemaLocation="urn:yahoo:maps http://api.local.yahoo.com/MapsService/V1/GeocodeResponse.xsd"><Result precision="zip"><Latitude>43.733514</Latitude><Longitude>-88.568017</Longitude><Address></Address><City>Fond Du Lac</City><State>WI</State><Zip></Zip><Country>US</Country></Result><Result precision="zip"><Latitude>39.708718</Latitude><Longitude>-105.597875</Longitude><Address></Address><City>Idaho Springs</City><State>CO</State><Zip></Zip><Country>US</Country></Result><Result precision="zip"><Latitude>41.223383</Latitude><Longitude>-79.632066</Longitude><Address></Address><City>Salem Twp</City><State>PA</State><Zip></Zip><Country>US</Country></Result><Result precision="zip"><Latitude>33.392225</Latitude><Longitude>-93.288924</Longitude><Address></Address><City>Waldo</City><State>AR</State><Zip></Zip><Country>US</Country></Result></ResultSet>

<!-- ws04.ydn.re2.yahoo.com compressed/chunked Sun Aug  9 13:03:57 PDT 2009 -->
